-- Insert waste categories into the database
INSERT INTO waste_category (name, description) VALUES ('Plastic', 'Non-biodegradable waste made from synthetic or semi-synthetic organic compounds. Includes items like bottles, bags, and packaging materials.');
INSERT INTO waste_category (name, description) VALUES ('Organic', 'Biodegradable waste from natural sources, such as food scraps, garden waste, and agricultural byproducts.');
INSERT INTO waste_category (name, description) VALUES ('Electronic', 'Waste from electronic devices and gadgets, such as old phones, computers, and appliances (e-waste).');
INSERT INTO waste_category (name, description) VALUES ('Metal', 'Waste made from metals, including aluminum cans, scrap metal, and metal containers.');
INSERT INTO waste_category (name, description) VALUES ('Glass', 'Non-biodegradable waste made from glass materials, such as bottles, jars, and broken glass.');
INSERT INTO waste_category (name, description) VALUES ('Paper', 'Waste made from paper products, such as newspapers, cardboard, and office paper.');
INSERT INTO waste_category (name, description) VALUES ('Textile', 'Waste generated from clothing, fabric, and other textile materials.');
INSERT INTO waste_category (name, description) VALUES ('Construction and Demolition (C&D)', 'Waste from construction and demolition activities, such as concrete, bricks, wood, and drywall.');
INSERT INTO waste_category (name, description) VALUES ('Hazardous', 'Waste that poses a potential risk to human health or the environment, such as chemicals, batteries, and medical waste.');
INSERT INTO waste_category (name, description) VALUES ('Medical/Biomedical', 'Waste generated from medical facilities, such as syringes, bandages, and pharmaceutical waste.');
INSERT INTO waste_category (name, description) VALUES ('Rubber', 'Waste made from rubber materials, such as tires, rubber bands, and rubberized products.');
INSERT INTO waste_category (name, description) VALUES ('Wood', 'Waste generated from wooden materials, such as furniture, pallets, and untreated wood scraps.');
INSERT INTO waste_category (name, description) VALUES ('Plastic Composite', 'Waste made from mixed materials that include plastic, such as Tetra Pak cartons and composite packaging.');
INSERT INTO waste_category (name, description) VALUES ('Chemical', 'Waste from industrial or household chemicals, such as solvents, detergents, and fertilizers.');
INSERT INTO waste_category (name, description) VALUES ('Ash', 'Residue from burning materials, such as coal ash or wood ash.');
INSERT INTO waste_category (name, description) VALUES ('Ceramic', 'Waste made from ceramic materials, such as pottery, tiles, and porcelain.');
INSERT INTO waste_category (name, description) VALUES ('Food Waste', 'Waste from discarded or spoiled food products, including kitchen scraps and leftovers.');
INSERT INTO waste_category (name, description) VALUES ('Green Waste', 'Biodegradable waste from gardens and parks, such as grass clippings, leaves, and branches.');
INSERT INTO waste_category (name, description) VALUES ('Leather', 'Waste generated from leather products, such as shoes, belts, and bags.');
INSERT INTO waste_category (name, description) VALUES ('Municipal Solid Waste (MSW)', 'General household waste, including mixed materials that are not sorted.');
INSERT INTO waste_category (name, description) VALUES ('Industrial Waste', 'Waste from industrial processes, such as slag, tailings, and manufacturing debris.');
INSERT INTO waste_category (name, description) VALUES ('Nuclear', 'Radioactive waste generated from nuclear power plants, medical treatments, or research.');
INSERT INTO waste_category (name, description) VALUES ('Paint and Coatings', 'Waste from leftover paints, varnishes, and other surface treatments.');
INSERT INTO waste_category (name, description) VALUES ('Packaging', 'Waste from packaging materials, including bubble wrap, Styrofoam, and cardboard boxes.');
INSERT INTO waste_category (name, description) VALUES ('Composite Materials', 'Waste from mixed materials like carbon fiber or fiberglass.');
